### PR TITLE
Add Webpack config to allow SVG rendering on Web

### PR DESCRIPTION
**Pull request by kristerkari**

### CODE REVIEW

**Comment by Cogneter** [comment]
I tested this and it works, thanks! Hope it gets added to the official package.

**Review by raqso — APPROVED** [review]

**Comment by fatidian1** [comment]
It's not working with style attribute in svg - for example:
`import LogoVertical from "../../assets/images/logo-vertical.svg";`
`<LogoVertical width={200} height={80} style={{marginBottom: 20}} />`
The error is "The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX."

**Comment by kristerkari** [comment]
Expo still hasn't upgraded to Webpack 5 (Expo is using v4), which makes this more complicated than it should be since SVGR is using Webpack 5.

**Comment by Swiftwork** [comment]
@kristerkari After some digging today I came to the same conclusion. However, your webpack config didn't work for me. It still removed the viewbox. I assume this is due to the silly format svgoConfig used back then. I did some legacy digging and found this to be working better. However, I could not verify that the inlineStyles rule was correct. Unsure of how to specify the params (saw the config below in a few places on the internet). Sharing in case it helps someone else.

```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Add new rules to the oneOf containing all previously defined rules
  // Overwrite options due to lack of webpack 5 support
  config.module.rules[1].oneOf.unshift({
    test: /\.svg$/,
    exclude: /node_modules/,
    use: [
      {
        loader: '@svgr/webpack',
        options: {
          svgoConfig: {
            plugins: [
              {
                name: 'removeViewBox',
                active: false,
              },
              {
                name: 'removeUnknownsAndDefaults',
                active: false,
              },
              {
                name: 'convertColors',
                active: false,
              },
              {
                name: 'inlineStyles',
                params: {
                  onlyMatchedOnce: false,
                },
              },
            ],
          },
        },
      },
    ],
  });
  return config;
};

```

**Comment by kristerkari** [comment]
@Swiftwork Thanks for sharing!

**Comment by RicardoBrito1938** [comment]
> ```js
> @svgr/webpack
> ```

something add, who is on SDK 47, you need to install 

"@svgr/webpack": "5.0.0",

if you install a newer version, it going to generate another error

**Comment by bombillazo** [comment]
None of the provided solutions is working for me :/ In my case I am using Next with Expo.

**Comment by kristerkari** [comment]
I can have a look at this again when I have some free time. It's a bit tricky because of the Webpack version problem that I mentioned earlier.

**Comment by bgilbert6** [comment]
@kristerkari @bombillazo 
Make sure to install the version of svgr that works with webpack 4:
`npm i @svgr/webpack@5.5.0 --save-dev`

**Comment by meedwire** [comment]
> @kristerkari After some digging today I came to the same conclusion. However, your webpack config didn't work for me. It still removed the viewbox. I assume this is due to the silly format svgoConfig used back then. I did some legacy digging and found this to be working better. However, I could not verify that the inlineStyles rule was correct. Unsure of how to specify the params (saw the config below in a few places on the internet). Sharing in case it helps someone else.
> 
> ```js
> const createExpoWebpackConfigAsync = require('@expo/webpack-config');
> 
> module.exports = async function (env, argv) {
>   const config = await createExpoWebpackConfigAsync(env, argv);
>   // Add new rules to the oneOf containing all previously defined rules
>   // Overwrite options due to lack of webpack 5 support
>   config.module.rules[1].oneOf.unshift({
>     test: /\.svg$/,
>     exclude: /node_modules/,
>     use: [
>       {
>         loader: '@svgr/webpack',
>         options: {
>           svgoConfig: {
>             plugins: [
>               {
>                 name: 'removeViewBox',
>                 active: false,
>               },
>               {
>                 name: 'removeUnknownsAndDefaults',
>                 active: false,
>               },
>               {
>                 name: 'convertColors',
>                 active: false,
>               },
>               {
>                 name: 'inlineStyles',
>                 params: {
>                   onlyMatchedOnce: false,
>                 },
>               },
>             ],
>           },
>         },
>       },
>     ],
>   });
>   return config;
> };
> ```

This works very well, I haven’t explored how far it is possible to go with this, but it seems promising, maybe open a PR?

**Comment by kristerkari** [comment]
Merged, as the config works now that Expo has added support for Webpack v5.

**Comment by ralyodio** [comment]
how do i use with latest expo? I'm also getting erorrs with imported svgs when doing `npm run web`

**Pull request merged**
